name: DZ4

on:
#    push
  schedule:
    - cron: '1 */6 * * *'

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '22'
      - name: "Использование ветки main репозитория"
        uses: actions/checkout@v3

      - name: "Запуск тестов для компьютерной версии сайта"
        run: mvn clean test -Dtest=MtsBankTest
        continue-on-error: true
      - name: "Запуск тестов для мобильной версии сайта"
        run: mvn clean test -Dtest=MtsBankMobileTest
        continue-on-error: true
      - name: "Генерация allure-report"
        uses: simple-elf/allure-report-action@master
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: target/allure-report
          allure_history: target/allure-history

      - name: "Создание ветки gh-pages содержащей allure report"
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: target/allure-history